echo Executing NeXTTool to upload /home/robo/nxtOSEK/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
wineconsole /home/robo/bricxcc/NeXTTool.exe /COM=usb -firmware=/home/robo/nxtOSEK/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
